backend:
  name: github
  repo: TheFullResolution/gatsby-starter

media_folder: "static/images"
public_folder: "images"

collections:
  - label: "Pages"
    name: "pages"
    files:
      - label: "Meta Data"
        name: "metaData"
        file: cms/content/metaData.json
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Description, name: description, widget: string }
          - label: "Banner"
            name: "banner"
            widget: "image"
            media_library:
              config:
                multiple: false
      - label: "Home"
        name: "home"
        file: cms/content/home.json
        fields:
          - { label: Title, name: title, widget: string }
